backend:
  name: git-gateway # üëà DEVE ESSERE QUESTO
  repo: marylou90/antonellino
  branch: main
  
# ‚ùó BLOCCO AUTH0 CORRETTO: 
# Utilizza il dominio e il Client ID che hai configurato in Auth0
auth:
  provider: auth0
  # Dominio del tuo account Auth0 (es. dev-4yo3p57jb27ie4qp.eu.auth0.com)
  site_domain: 'dev-4yo3p57jb27ie4qp.eu.auth0.com'
  # Client ID della tua applicazione Auth0
  app_id: 'a85gJGJkf36yAPrzhTojwcgcRr0mpDmU' 

  # ‚ö†Ô∏è AGGIUNGI IL CLAIM NAME DALL'AZIONE AUTH0 (Cruciale per i permessi GitHub)
  auth_config:
    github_access_token_claim: 'https://antonellino.io/github_access_token'

media_folder: assets/uploads
public_folder: /assets/uploads

collections:
  - name: "vini_e_cantine"
    label: "Vini e Cantine"
    folder: "_vini_e_cantine"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string", required: true}
      - {label: "Data di Pubblicazione", name: "date", widget: "datetime"}
      - {label: "Immagine in Evidenza", name: "image", widget: "image", required: false, hint: "Immagine principale per la sezione"}
      - {label: "Contenuto", name: "body", widget: "markdown"}

  - name: "ristoranti_e_osterie"
    label: "Ristoranti e Osterie"
    folder: "_ristoranti_e_osterie"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string", required: true}
      - {label: "Data di Pubblicazione", name: "date", widget: "datetime"}
      - {label: "Immagine in Evidenza", name: "image", widget: "image", required: false, hint: "Immagine principale per la sezione"}
      - {label: "Contenuto", name: "body", widget: "markdown"}