backend:
  name: github
  repo: marylou90/antonellino
  branch: main
  # auth_endpoint: URL di autorizzazione su Auth0 che la CMS aprirà in popup.
  # Nota: l'URL è composto per la response_type che restituisce id_token e token
  auth_endpoint: "https://dev-4yo3p57jb27ie4qp.eu.auth0.com/authorize?response_type=id_token%20token&scope=openid%20profile%20email&client_id=a85gJGJkf36yAPrzhTojwcgcRr0mpDmU&redirect_uri=https://dev-4yo3p57jb27ie4qp.eu.auth0.com/continue"

media_folder: assets/uploads
public_folder: /assets/uploads

collections:
  - name: "vini_e_cantine"
    label: "Vini e Cantine"
    folder: "_vini_e_cantine"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string", required: true}
      - {label: "Data di Pubblicazione", name: "date", widget: "datetime"}
      - {label: "Immagine in Evidenza", name: "image", widget: "image", required: false, hint: "Immagine principale per la sezione"}
      - {label: "Contenuto", name: "body", widget: "markdown"}

  - name: "ristoranti_e_osterie"
    label: "Ristoranti e Osterie"
    folder: "_ristoranti_e_osterie"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string", required: true}
      - {label: "Data di Pubblicazione", name: "date", widget: "datetime"}
      - {label: "Immagine in Evidenza", name: "image", widget: "image", required: false, hint: "Immagine principale per la sezione"}
      - {label: "Contenuto", name: "body", widget: "markdown"}